version: "3"
services:
  backend:
    image: hackerbone/jolteon:latest
    restart: always
    ports:
      - "8010:8010"
    env_file:
      - ./.env

  nginx:
    image: hackerbone/jolteon-nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
